version: "3.9"
services:
  web:
   build: 
      context: .
   image: flask
   ports:
      - "${APP_PORT}:5000"
   depends_on : 
     - db
  db:
   image: mysql:latest
   env_file:
     - .env 

  
    
